### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by SuperDasMan** [SuperDasMan/Taskinator#1]
Title: Initial Setup

## Requirements
* Create the task tracking HTML page that needs a:
   * Header
   * Main content area for the task list
   * Footer
* Use the style sheet provided
* Add functionality to the button to add tasks to the list

**Comment by Richard5656** [comment]
Is this a solo project or would you like some help?

**Comment by SuperDasMan** [comment]
Hello!

This is a solo project for the web dev class I'm taking, but I appreciate
your offer to help.

~Josh

**Comment by Richard5656** [comment]
Oh ok.
